# Generated by Django 3.1.1 on 2020-09-23 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='GeoPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lon', models.DecimalField(decimal_places=5, max_digits=7)),
                ('lat', models.DecimalField(decimal_places=5, max_digits=7)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='gps_tracker.route')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
