# Generated by Django 3.1.1 on 2020-09-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geopoint',
            old_name='route_id',
            new_name='route',
        ),
    ]
