# Generated by Django 3.1.1 on 2020-09-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_tracker', '0002_auto_20200924_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopoint',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
        migrations.AlterField(
            model_name='geopoint',
            name='lon',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
    ]
