# Generated by Django 3.1.1 on 2020-09-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps_tracker', '0004_auto_20200929_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geopoint',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='geopoint',
            name='created',
        ),
        migrations.RemoveField(
            model_name='route',
            name='created',
        ),
    ]
